namespace Mirance.iOSUSB;

public enum STATE_CODE
{
	None = -999,
	ERROR_NOT_FOUND_IOS_DEVICE = -1,
	ERROR_PORT_ALREADY_BIND = -2,
	ERROR_NO_DRIVER = -3,
	PROGRESS_PERCENT_10 = 1,
	PROGRESS_PERCENT_20 = 2,
	PROGRESS_PERCENT_30 = 3,
	PROGRESS_PERCENT_40 = 4,
	PROGRESS_PERCENT_50 = 5,
	PROGRESS_PERCENT_60 = 6,
	PROGRESS_PERCENT_70 = 7,
	PROGRESS_PERCENT_80 = 8,
	PROGRESS_PERCENT_90 = 9,
	PROGRESS_PERCENT_100 = 10,
	CONNECT_SUCCESS = 11,
	MSG_NEED_USER_TRUST = 21,
	MSG_SCREEN_DESTORY = 22,
	MSG_DEVICE_CHANGE = 23,
	MSG_DEVICE_REMOVE = 24
}
