name: Build and Release Mirance.exe

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore
      run: dotnet restore src/Mirance.sln
        
    - name: Build
      run: dotnet build src/Mirance.sln -c Release --no-restore
        
    - name: Create release folder
      run: mkdir Mirance
        
    - name: Copy built files
      run: |
        Copy-Item -Path "src/Mirance.App\bin\Release\net8.0-windows\*" -Destination "Mirance\" -Recurse -Force
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Mirance-bin
        path: Mirance/
        retention-days: 30
